name: ğŸ”® CI - Main checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: config.settings_test
    strategy:
      matrix:
        # Only include the first and last supported Python versions, as well as
        # the one that is pinned in the .python-version file
        # (which should be the default one on Scalingo, per
        # https://doc.scalingo.com/languages/python/start )
        python-version: ["3.10", "3.13", "3.14"]
        # Only include the first and last supported pgsql versions to limit
        # the number of jobs
        postgresql-version: [14, 17]
    services:
      postgres:
        image: postgres:${{ matrix.postgresql-version }}-alpine
        env:
          POSTGRES_USER: dju
          POSTGRES_PASSWORD: djpwd
          POSTGRES_DB: djdb
          POSTGRESQL_VERSION: ${{ matrix.postgresql-version }}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: ğŸ“” Install just
        uses: extractions/setup-just@v2
      - name: ğŸ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: ğŸ Set up uv
        uses: astral-sh/setup-uv@v5
      - uses: pre-commit/action@v3.0.1
      - name: ğŸŒ Install dependencies
        run: |
          uv sync --no-group dev
      - name: ğŸ“„ Copy empty .env.test to .env
        run: |
          cp .env.test .env
      - name: ğŸ’¾ Collect static files
        run: |
          just collectstatic
      - name: âœ¨ Black & ruff
        run: |
          just quality
      - name: ğŸ¤¹â€ Run the unit tests
        run: |
          just unittest
      - name: ğŸ¨ Deploy starter content
        run: |
          just init
          uv run python manage.py create_demo_pages
