name: üîÆ CI - Main checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: config.settings_test
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        # Only include the first and last supported pgsql versions to limit
        # the number of jobs
        postgresql-version: [13, 17]
    services:
      postgres:
        image: postgres:${{ matrix.postgresql-version }}-alpine
        env:
          POSTGRES_USER: dju
          POSTGRES_PASSWORD: djpwd
          POSTGRES_DB: djdb
          POSTGRESQL_VERSION: ${{ matrix.postgresql-version }}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: üêç Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: üåç Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install ruff
          poetry install --no-root  --with dev
      - name: üìÑ Copy empty .env.test to .env
        run: |
          cp .env.test .env
      - name: ‚ú® Black & ruff
        run: |
          make quality
      - name: ü§π‚Äç Run the unit tests
        run: |
          make test-unit
      - name: üé® Deploy starter content
        run: |
          make init
          poetry run python manage.py create_demo_pages
        env:
          DJANGO_DEBUG: True
